### ISSUE TITLE
 Issues loading network components in a specific order

### ISSUE THREAD

**Issue by mwytock** [cvxgrp/dem#1]
I modified your Static Grouping Devices Example slightly to interface 2 Groups:

        solar = Generator(power_max=10, alpha=0, beta=0, name="Solar")
        load = FixedLoad(power=13)
        line = TransmissionLine(power_max=25)
        net = Net([load.terminals[0], solar.terminals[0], line.terminals[0]])
        home = Group([solar, load, line], [net], [line.terminals[1]], name="Home")

        gen = Generator(power_max=1e6, alpha=0.05, beta=100, name="Grid")
        meter = Net([line.terminals[1], gen.terminals[0]], name="Meter")

        grid = Group([gen],[meter])

        network = Group([home, grid], [])

        network.init_problem()
        network.problem.solve()
        print(network.results.summary())

This works as expected, but if you change the order of the Groups being loaded the program throws an exception.

        network = Group([grid, home], [])

It basically boils down to grid referencing a terminal _power level before it get initialized by the init_problem of the Transmission line.

I probably can avoid this, but then i can't just link up various groups, and will have to load every element individually. i guess i could pre-call init_problem on all transmission lines before i put them into groups.

I got around this issue temporarily with probably a poor solution of modifying the dem.network.Net class:

        class Net(object):
            ........
            def init_problem(self, time_horizon=1, num_scenarios=1):
                for terminal in self.terminals:
                    terminal._power = cvx.Variable(time_horizon, num_scenarios)
                self.constraints = [sum(t._power[:,k] for t in self.terminals) == 0 for k in range(num_scenarios)]
            ........

**Comment by echu** [comment]
Completely off topic (on this issue): so happy to see this project be a separate repo. :)

**Comment by mwytock** [comment]
Thanks Eric :)

**Comment by mwytock** [comment]
FYI - there are some subtleties around creating hierarchical devices and initialization order. Basic idea is that the `Terminal` defines the power variables and `Device` and `Net` define functions/constraints on those variables. As such, the variables associated with terminals should be initialized first but that wasn't happening in some cases with multiple `Group` devices.

**Comment by stephenpboyd** [comment]
Matt are you around for coffee after my faculty meeting soon?
