### ISSUE TITLE
Default TransmissionLine power_max not valid

### ISSUE THREAD

**Issue by djohnsonbaugh** [cvxgrp/dem#6]
There are many cases where a line may not be monitored but is still relevant to the system.

TransmissionLine power_max defaults to None but causes solutions to fail.

Potentially check for power_max=None and don’t enforce the 2nd constraint when it is true. This could greatly reduce the number of constraints if TransmissionLines are created with power_max = None instead of power_max = 99999

**Comment by djohnsonbaugh** [comment]
>     @property
    def constraints(self):
        if self.power_max==None:
            return [self.terminals[0].power_var + self.terminals[1].power_var == 0]
        else:
            return [
                self.terminals[0].power_var + self.terminals[1].power_var == 0,
                (cvx.abs((self.terminals[0].power_var -
                          self.terminals[1].power_var)/2) <= self.power_max)
            ]

**Comment by mwytock** [comment]
makes sense will change
